sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build --build-arg GITHUB_PAT=$GITHUB_ACCESS_TOKEN -t docker-airflow .
      - docker images
      - docker tag docker-airflow $DOCKER_USERNAME/docker-airflow:1.10.2
      - docker push $DOCKER_USERNAME/docker-airflow:1.10.2
